import{a as S,S as v,i as s}from"./assets/vendor-CIF6YjI2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))m(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&m(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function m(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const q="56165322-4eccb7c267e8fea85df72b379",g=async(e,o)=>(await S.get("https://pixabay.com/api/",{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data,y=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),P=new v(".gallery a",{});function M(e){return`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <ul class="gallery-item-desc">
        <li>Likes <p>${e.likes}</p></li>
        <li>Views <p>${e.views}</p></li>
        <li>Comments <p>${e.comments}</p></li>
        <li>Downloads <p>${e.downloads}</p></li>
      </ul>
    </li>
  `}function $(e){return e.map(M).join("")}function L(e){y.insertAdjacentHTML("beforeend",$(e)),P.refresh()}function O(){y.innerHTML=""}function w(){p.classList.add("loader--visible")}function i(){p.classList.remove("loader--visible")}function x(){h.classList.remove("load-more--hidden")}function l(){h.classList.add("load-more--hidden")}const f=document.querySelector(".form"),B=document.querySelector(".load-more");let d="",n=1,u=0;l();f.addEventListener("submit",async e=>{e.preventDefault();const o=f.querySelector('[name="search-text"]').value.trim();if(!o){s.warning({message:"Please enter a search term."});return}d=o,n=1,u=0,O(),l(),w();try{const a=await g(d,n);if(i(),a.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}u=a.totalHits,L(a.hits),b()}catch{i(),s.error({message:"Something went wrong. Please try again."})}});B.addEventListener("click",async()=>{n+=1,l(),w();try{const e=await g(d,n);i(),L(e.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),b()}catch{i(),s.error({message:"Something went wrong. Please try again."})}});function b(){n*15>=u?(l(),s.info({message:"We're sorry, but you've reached the end of search results."})):x()}
//# sourceMappingURL=index.js.map
